global using Microsoft.Extensions.Logging;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Exceptions;
global using System;
global using System.Collections.Generic;
global using System.Net.Sockets;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;