version: '3.8'

services:
  eventdrive.worker.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  eventdrive.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
